# Generated by Django 4.2.6 on 2024-04-24 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(blank=True, choices=[('Muebles', 'Muebles'), ('Electrodomesticos', 'Electrodomesticos'), ('Celulares', 'Celulares')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
