# Generated by Django 4.2.6 on 2024-04-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_is_active_remove_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
